image:
- Visual Studio 2017
- Ubuntu

stack: python 3

environment:
  PYTHON: "C:\\Python36-x64"
  PYTHON_VERSION: "3.6.x"
  PYTHON_ARCH: "64"

init:
- cmd: "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

install:
- python -V
- pip -V
- pip install --user pyTelegramBotAPI
- pip install --user requests[socks]
- pip install --user PyYAML

build: off

test_script:
- python run.py
