environment:
  matrix:
  - PYTHON: "C:\\Python36"
    PYTHON_VERSION: "3.6.x"
    PYTHON_ARCH: "32"

  - PYTHON: "C:\\Python36-x64"
    PYTHON_VERSION: "3.6.x"
    PYTHON_ARCH: "64"

install:
- "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
- python -V
- pip -V
- pip install --user pyTelegramBotAPI
- pip install --user requests[socks]
- pip install --user PyYAML

test_script:
- python speechbot\bot.py

build: off